name: snaps
favicon: null
layout_spectrum: 0.03575536189600825
typography_spectrum: 0.5463995805475861
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.867753230035305
  lightness: 0.7904210088308901
  saturation: 0.49784318334423006
  rhythmicContrast: 0.901570554357022
purpose: []
